### ISSUE TITLE
Cant easily select scrollbar

### ISSUE THREAD

**Issue by leosilvano** [holmar/brackets-no-distractions-advanced#2]
![scrollbar](https://cloud.githubusercontent.com/assets/7308822/13109596/64a90970-d561-11e5-8a34-eb0a98171a79.gif)
Is is possible to make the plugin toolbar show up only when you touch the edge of the screen?

**Comment by holmar** [comment]
Hi, thanks for the report!

This is now fixed in v1.0.1. The toolbar will only be shown when touching the edge.

PS: Sorry for the late response, GitHub notifications went into my spam folder for some reason …
