### ISSUE TITLE
Cant get extensions bar back when disabling/ uninstalling

### ISSUE THREAD

**Issue by HugoMcPhee** [holmar/brackets-no-distractions-advanced#3]
HI, When disabling or uninstalling, the extensions bar on the right doesn't re-appear
(the panel on the left stays hidden but can be shown by dragging it into view)
Is there way to get the right panel to show again?
Thanks

**Comment by holmar** [comment]
Did you restart Brackets after disabling/removing the extension? Also, you might still be in "No Distractions" view – uncheck `View → No Distractions` to turn it off. This is a Brackets core feature that doesn't get set by the extension.

So, to sum up:
1) Disable the extension
2) Brackets prompts for a restart, so restart
3) Turn off "No Distractions" by unchecking `View → No Distractions`

Let me know if you followed these steps and one of the panels is still missing.

**Comment by HugoMcPhee** [comment]
that was it, disabling "No Distractions" mode in view worked
thanks
